#index:
#    path: /
#    controller: App\Controller\DefaultController::index
episodes:
  path: /{feedUrl}
  controller: App\Controller\RssFeedController::generatePodcastSite
  defaults:
    feedUrl:
